# Project Information
site_name: अस्थायी टिप्पणी पुस्तक
site_description: बाद में उपयोग के लिए कुछ अनियमित टिप्पणियाँ।
site_author: Abhijit Bose (aka. boseji)
copyright: >-
  Copyright &copy; 1998 - 2024 
  <a href="https://github.com/boseji" targe="_blank" rel="noopener">Abhijit Bose (aka. boseji)</a>. 
  All rights reserved. Unless otherwise specified, content licensed under
  <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" targe="_blank" rel="noopener"><code style="background-color: indigo;color: white;font-size: +1.3em;">SPDX: CC-BY-NC-ND-4.0</code></a>

# Site Configuration
docs_dir: act/docs
use_directory_urls: true
strict: true
site_dir: public

# Theme Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: lime
      toggle:
        icon: material/flare
        name: Dark mode

    # Palette toggle for dark mode (Default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: light green
      toggle:
        icon: material/weather-night
        name: Light mode

  font:
    text: Open Sans
    # code: Consolas

  icon:
    # logo: material/gamepad-variant
    repo: fontawesome/brands/github
    # edit: material/file-edit-outline
    # view: material/file-eye-outline
  # favicon: _site/favicon.ico

extra:
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  extra_css:
    - _site/mkdocs-extra.css
  extra_javascript:

plugins:
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - no-sitemap
  - mkdocs-video:
      video_controls: True
      css_style:
        width: "60vw"
        height: "30vw"
        # width: "560"
        # height: "320"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.escapeall:
      hardbreak: false
      nbsp: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: "+"
      key_map:
        click: "Click"
        left-click: "Left Click"
        right-click: "Right Click"
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
